---
- name: OS Hardening Playbook
  hosts: all
  become: yes

  tasks:

    - name: Add specific firewall rules
      firewalld:
        service: "{{ item }}"
        state: enabled
        immediate: yes
      loop:
        - ssh
        - http
        - https

    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      notify:
        - restart sshd

    - name: Ensure password authentication is disabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify:
        - restart sshd

    - name: Ensure SSH protocol is set to 2
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Protocol'
        line: 'Protocol 2'
      notify:
        - restart sshd

    - name: Disable unused network protocols
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - telnet
        - rsh-server
        - rsh
        - ypserv
        - tftp
        - tftp-server

    - name: Remove insecure packages
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - rsh
        - telnet
        - finger

    - name: Ensure permissions on /etc/shadow are properly set
      file:
        path: /etc/shadow
        owner: root
        group: root
        mode: '0000'

    - name: Disable unused services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - rpcbind
        - nfs
        - nfs-server
        - nfs-lock
        - nfs-idmap
    
    - name: Allow SSH
      ufw:
        rule: allow
        name: 'OpenSSH'

    - name: Allow specific ports
      ufw:
        rule: allow
        port: '{{item}}'
      loop:
        - '80'
        - '443'
    
    - name: Initialize AIDE
      command: /usr/sbin/aide --init
      args:
        creates: /var/lib/aide/aide.db.new.gz
    
    - name: Copy the AIDE database
      copy:
        src: /var/lib/aide/aide.db.new.gz
        dest: /var/lib/aide/aide.db.gz
        remote_src: yes

    - name: Ensure AppArmor is enabled in boot params
      lineinfile: 
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=".*'
        line:'GRUB_CMDLINE_LINUX_DEFAULT="apprarmor=1 security=apparmor'
      notify: update-grub
    
    - name: Load AppArmor profiles
      command: "aa-enforce /etc/apparmor.d"

    - name: update-grub
      command: grub2-mfconfig -o /boot/grub2/grub.config