---
- name: Restart auditd and remount filesystems
  hosts: all
  become: yes

  tasks:
    - name: Restart auditd via systemd
      systemd:
        name: auditd
        state: restarted

    - name: Remount filesystems
      mount:
        name: /
        state: remounted
      notify:
        - reload systemd
        - reload auditd

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
        state: reloaded

    - name: reload auditd
      service:
        name: auditd
        state: reloaded
